### ISSUE TITLE
Getting error during subscribe user to list

### ISSUE THREAD

**Issue by mohdbashir** [Sammaye/yii2-mailchimp#3]
```
$mc = new \sammaye\mailchimp\Mailchimp(['apikey' => 'XXXXXX]);
$result = $mc->lists->subscribe('18069','abc@test.com','abcxyz','html',false,true,false,false);
echo '<pre>';print_r($result);die;
```

Using the above code and getting error: 

Mailchimp_Error
We received an unexpected error: null

```
 in /var/www/html/heminidev/trunk/vendor/mailchimp/mailchimp/src/Mailchimp.php at line 249
                return $apikey;
            }
        }
    }
    return false;
} 
public function castError($result) {
    if ($result['status'] !== 'error' || !$result['name']) {
        throw new Mailchimp_Error('We received an unexpected error: ' . json_encode($result)); // line 249
    }
```

**Comment by Sammaye** [comment]
Sorry for not replying I forgot all about this.

Anyway, I know what the problem is and it is one of two things:
- Your API key is dodgy and you need to get a new one
- The mailchimp API servers are having a bad day

In fact the second one is how I found this thread in my emails.

**Comment by mohdbashir** [comment]
It is working.
$mc = new \sammaye\mailchimp\Mailchimp(['apikey' => 'XXXXXX]);
$result = $mc->call('lists/subscribe', array(                
                        'id'                => 'xxxxxx',
                        'email'             => array('email'=>'xxx@xxx.xxx',),
                        'merge_vars'        => array('FNAME'=>'john', 'LNAME'=>'doe'),
                        'double_optin'      => false,
                        'update_existing'   => true,
                        'replace_interests' => false,
                        'send_welcome'      => false,
                    ));
